Check for toolchain file

diff --git a/.github/workflows/update-subtree.yml b/.github/workflows/update-subtree.yml
--- a/.github/workflows/update-subtree.yml
+++ b/.github/workflows/update-subtree.yml
@@ -37,6 +37,11 @@ jobs:
       - name: Read date from rust-toolchain.toml
         working-directory: kani
         run: |
+          if [ ! -f "rust-toolchain.toml" ]; then
+            echo "Error: rust-toolchain file not found in the working directory."
+            exit 1
+          fi
+
           TOOLCHAIN_DATE=$(grep 'channel.*=.*"nightly-' ./rust-toolchain.toml | sed -E 's/.*nightly-([0-9-]+).*/\1/')
           if [ -z "$TOOLCHAIN_DATE" ]; then
             echo "Error: Could not extract date from rust-toolchain file."
